
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table zoomOut;

	private global::Gtk.Button moveEast;

	private global::Gtk.Button moveNorth;

	private global::Gtk.Button moveSouth;

	private global::Gtk.Button moveWest;

	private global::Gtk.Image tmImageBox;

	private global::Gtk.Button zoomIn;

	private global::Gtk.Button zoomOut1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.zoomOut = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.zoomOut.Name = "zoomOut";
		this.zoomOut.RowSpacing = ((uint)(6));
		this.zoomOut.ColumnSpacing = ((uint)(6));
		// Container child zoomOut.Gtk.Table+TableChild
		this.moveEast = new global::Gtk.Button();
		this.moveEast.CanFocus = true;
		this.moveEast.Name = "moveEast";
		this.moveEast.UseUnderline = true;
		this.moveEast.Label = global::Mono.Unix.Catalog.GetString("East");
		this.zoomOut.Add(this.moveEast);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.moveEast]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.moveNorth = new global::Gtk.Button();
		this.moveNorth.CanFocus = true;
		this.moveNorth.Name = "moveNorth";
		this.moveNorth.UseUnderline = true;
		this.moveNorth.Label = global::Mono.Unix.Catalog.GetString("North");
		this.zoomOut.Add(this.moveNorth);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.moveNorth]));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.moveSouth = new global::Gtk.Button();
		this.moveSouth.CanFocus = true;
		this.moveSouth.Name = "moveSouth";
		this.moveSouth.UseUnderline = true;
		this.moveSouth.Label = global::Mono.Unix.Catalog.GetString("South");
		this.zoomOut.Add(this.moveSouth);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.moveSouth]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.moveWest = new global::Gtk.Button();
		this.moveWest.CanFocus = true;
		this.moveWest.Name = "moveWest";
		this.moveWest.UseUnderline = true;
		this.moveWest.Label = global::Mono.Unix.Catalog.GetString("West");
		this.zoomOut.Add(this.moveWest);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.moveWest]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.tmImageBox = new global::Gtk.Image();
		this.tmImageBox.Name = "tmImageBox";
		this.zoomOut.Add(this.tmImageBox);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.tmImageBox]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.zoomIn = new global::Gtk.Button();
		this.zoomIn.CanFocus = true;
		this.zoomIn.Name = "zoomIn";
		this.zoomIn.UseUnderline = true;
		this.zoomIn.Label = global::Mono.Unix.Catalog.GetString("Zoom In");
		this.zoomOut.Add(this.zoomIn);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.zoomIn]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child zoomOut.Gtk.Table+TableChild
		this.zoomOut1 = new global::Gtk.Button();
		this.zoomOut1.CanFocus = true;
		this.zoomOut1.Name = "zoomOut1";
		this.zoomOut1.UseUnderline = true;
		this.zoomOut1.Label = global::Mono.Unix.Catalog.GetString("Zoom Out");
		this.zoomOut.Add(this.zoomOut1);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.zoomOut[this.zoomOut1]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.zoomOut);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 692;
		this.DefaultHeight = 367;
		this.Show();
		this.zoomOut1.Clicked += new global::System.EventHandler(this.OnZoomOut1Clicked);
		this.zoomIn.Clicked += new global::System.EventHandler(this.OnZoomInClicked);
		this.moveWest.Clicked += new global::System.EventHandler(this.OnMoveWestClicked);
		this.moveSouth.Clicked += new global::System.EventHandler(this.OnMoveSouthClicked);
		this.moveNorth.Clicked += new global::System.EventHandler(this.OnMoveNorthClicked);
		this.moveEast.Clicked += new global::System.EventHandler(this.OnMoveEastClicked);
	}
}
